#基础信息
title: Edward的博客
email: 250740918@qq.com
url: da6.ren
avatar: https://github.com/account
description: 有艺术的程序员

#文档配置
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart

#高亮配置
highlight-theme : my-github

#评论配置
#disqus: fishedee

#统计配置
#baidu: 0a6da8c751d798199236954c919fd59e


